version: '3'
services:
  API:
    container_name: inethi-music-share-api
    build: ./
    restart: always
    links:
      - music-mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=${API_RULE}"
      - "traefik.http.routers.api.entrypoints=${API_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"

  music-wordpress:
    image: wordpress:latest
    container_name: inethi-musicshare-wordpress
    volumes:
      - "{$MUSIC_SHARE_WORDPRESS_MOUNT}:/var/www/html"
      - "{$MUSIC_SHARE_WORDPRESS_MOUNT_INI_FILE}:/usr/local/etc/php/conf.d/uploads.ini"
      - "{$MUSIC_SHARE_WORDPRESS_MOUNT_CONTENT_FOLDER}:/var/www/html/wp-content"
    environment:
      - "WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}"
      - "WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}"
      - "WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}"
      - "WORDPRESS_DB_USER=${WORDPRESS_DB_USER}"
      - "WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}"
    depends_on:
      - music-mariadb
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=${WORDPRESS_RULE}"
      - "traefik.http.routers.wordpress.entrypoints=${WORDPRESS_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"

  music-mariadb:
    image: mariadb/server:10.4
    container_name: inethi-musicshare-mariadb
    hostname: inethi-musicshare-mariadb
    domainname: inethi-musicshare-mariadb.inethi.net
    volumes:
      - "{$MUSIC_SHARE_MARIADB_MOUNT}:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_USER=${WORDPRESS_DB_USER}"
      - "MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}"
      - "MYSQL_DATABASE=${WORDPRESS_DB_NAME}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb.rule=${MARIADB_RULE}"
      - "traefik.http.routers.mariadb.entrypoints=${MARIADB_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"

  adminer:
    image: adminer
    container_name: inethi-musicshare-adminer
    restart: always
    links:
      - music-mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=${ADMINER_RULE}"
      - "traefik.http.routers.adminer.entrypoints=${ADMINER_ENTRYPOINT}"
    networks:
      - "${INETHI_NETWORK}"

networks:
  web:
    external: true


